made nice output for github forward hook

diff --git a/post-receive b/post-receive
--- a/post-receive
+++ b/post-receive
@@ -88,7 +88,14 @@ fi
 
 if [ "$pushToGitHub" = "true" ]
 then
-    git push github ${refname:t}
+    echo -e "\nForward push to GitHub"
+    if ( git push github ${refname:t} )
+    then
+        echo -e "${Green}GitHub push SUCCESSFUL${Normal}\n"
+    else
+        echo -e "${Red}Could not push to GitHub.${Normal}\n"
+        exit 1
+    fi
 fi
 
 if [ "$publishHomeRepo" = "true" ]
